<?xml version="1.0" encoding="utf-8"?><html><style type="text/css">.t0{color:#ff0000;}.t1{color:#006400;}.t2{color:#808080;}.i0{display:inline-block;vertical-align:text-bottom;margin-right:2px;background:url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGqSURBVDhPrVPPSwJBFJ51Z91VK4XUvHlQpG4dBD0EXor+Bg9BBEWHbt07dCvo4H8QdAiiU6dOGXTREPKSUawQtJegNolCy92m962bJIgK9cHOvHnz3pv341v2V0ju3kUul+OGYSxLkpQRQqRp57RX6aqsqup+rVZ761h20BMglUpN27Z9mLGbs3PtdzZjt5gsBLvjGrvkfnamjN2TWV7X9VLH41cAOPutdmXj4zmw+PnqantRUgJsV4tYpiQv1Ov1c+g8WJA2Xh7kDGQpq63mIyfxIB6Ph6CTsXDOVyjttfXWE44DEfuymOnhE7rXb5mmWXQyQMNQ86iALTU26x4ZSyQSV8WYKh4i0A8GbG6iHpFMJl/g62RA0FQmXHE4UDfFQi+6ASo1WXMEIyoN/IBbWUXZ4EY3QBlzHhWurcMFJwAYBpJgzsOg0+tH3lCDxALOTgCXnvk9NWxVuQ+qvoDztm+K2ZK0Smw0oHN4ANBMDXUyfHGqjM9jzrgIChvG7JqofOINsh1ftNHw8CVyPu549fmZwDBFUTapy1lqVBrddhuGmgs/L/8TGPsGqyfFmWv0DOkAAAAASUVORK5CYII=') no-repeat;width:16px;height:16px;background-size: 16px 16px;}.i1{display:inline-block;vertical-align:text-bottom;margin-right:2px;background:url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE9SURBVDhPY6AUMEJpgkBZWfk8IyOjAZQLBnfu3GFkgrLxAqDmAGZxZgO+Uj4GEOaJ5wEJvwARRBkABPXsVuxQJgPDz2M/QVQniCBoAMx2VlVWMP/fq38Mv2//fvH79+8ZID4xLsBq+8OHD3+AGHgNIGQ7CIBjQUVF5T+YhwB3pKWlNZ88eXKaK5ALbsD3Dd9BBhQCQ38CWAAIYC64wx3BDQ5hEGaRZVEBal5OyHYQABsAjN/Wn0fBfgMDdmt2kFgIPr/DANgAKSmpJX8e/7nz9/FfsCCzLDMDmzEbAyHbQYAZRABN/ScsLPz538d/Aaw6EE0siixgGgR+7P7B8O/dv9r79+8fgQrBATwW0F0BA/hsBwG4AQcPHvyDHhYggMvvMICSmezt7VmePn16HchUgYiAAch2RVwGUAgYGAAwXKTZMwKWhgAAAABJRU5ErkJggg==') no-repeat;width:16px;height:16px;background-size: 16px 16px;}</style><body /><div><div style="margin-left: 0px"><i class="i0"></i><span class="richText"><span>GuiStracini.Mandae.Test</span></span> <span class="richText"><span>(27 tests)</span></span> <span class="richText"><span class="t0">[0:15.175] Failed: 13 tests failed</span></span></div><div style="margin-left: 20px"><i class="i0"></i><span class="richText"><span>GuiStracini.Mandae.Test</span></span> <span class="richText"><span>(27 tests)</span></span> <span class="richText"><span class="t0">[0:15.175] Failed: 13 tests failed</span></span></div><div style="margin-left: 40px"><i class="i1"></i><span class="richText"><span>CustomerTest</span></span> <span class="richText"><span>(2 tests)</span></span> <span class="richText"><span class="t1">[0:00.915] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>RegisterCustomer</span></span> <span class="richText"><span class="t1">[0:00.494] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>RegisterCustomerAsync</span></span> <span class="richText"><span class="t1">[0:00.420] Success</span></span></div><div style="margin-left: 40px"><i class="i0"></i><span class="richText"><span>FlowTest</span></span> <span class="richText"><span>(1 test)</span></span> <span class="richText"><span class="t0">[0:03.667] Failed: 1 test failed</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>FullFlowValidation</span></span> <span class="richText"><span class="t0">[0:03.667] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsTrue failed. 
   em GuiStracini.Mandae.Test.FlowTest.FullFlowValidation() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\FlowTest.cs:linha 127


</span></span></div><div style="margin-left: 40px"><i class="i0"></i><span class="richText"><span>OrdersTest</span></span> <span class="richText"><span>(10 tests)</span></span> <span class="richText"><span class="t0">[0:05.363] Failed: 10 tests failed</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>CancelOrderCollectRequest</span></span> <span class="richText"><span class="t0">[0:00.889] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsTrue failed. 
   em GuiStracini.Mandae.Test.OrdersTest.CancelOrderCollectRequest() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 209


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>CancelOrderCollectRequestAsync</span></span> <span class="richText"><span class="t0">[0:00.851] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsTrue failed. 
   em GuiStracini.Mandae.Test.OrdersTest.&lt;CancelOrderCollectRequestAsync&gt;d__8.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 223
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>CancelOrderItemCollectRequest</span></span> <span class="richText"><span class="t0">[0:00.461] Failed</span></span><br /><span class="richText"><span class="t2">Test method GuiStracini.Mandae.Test.OrdersTest.CancelOrderItemCollectRequest threw exception: 
System.AggregateException: Um ou mais erros. ---&gt; GuiStracini.Mandae.GoodPractices.InvalidRequestEndPointException: The endpoint ordersitems/123456 is not valid for the pattern orders/{OrderId}/items/{ItemId}
    em GuiStracini.Mandae.Utils.RequestHelpers.GetRequestEndPoint(BaseRequest request) na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\Utils\RequestHelpers.cs:linha 75
   em GuiStracini.Mandae.Utils.ServiceFactory.&lt;Execute&gt;d__5`2.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\Utils\ServiceFactory.cs:linha 86
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   em GuiStracini.Mandae.Utils.ServiceFactory.&lt;Delete&gt;d__13`2.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\Utils\ServiceFactory.cs:linha 213
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   em GuiStracini.Mandae.MandaeClient.&lt;CancelOrderItemCollectRequestAsync&gt;d__21.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\MandaeClient.cs:linha 361
--- End of inner exception stack trace ---
    em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   em System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   em System.Threading.Tasks.Task`1.get_Result()
   em GuiStracini.Mandae.MandaeClient.CancelOrderItemCollectRequest(Int64 orderId, Int64 itemId) na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\MandaeClient.cs:linha 343
   em GuiStracini.Mandae.Test.OrdersTest.CancelOrderItemCollectRequest() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 235


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>CancelOrderItemCollectRequestAsync</span></span> <span class="richText"><span class="t0">[0:00.439] Failed</span></span><br /><span class="richText"><span class="t2">Test method GuiStracini.Mandae.Test.OrdersTest.CancelOrderItemCollectRequestAsync threw exception: 
GuiStracini.Mandae.GoodPractices.InvalidRequestEndPointException: The endpoint ordersitems/123456 is not valid for the pattern orders/{OrderId}/items/{ItemId}
    em GuiStracini.Mandae.Utils.RequestHelpers.GetRequestEndPoint(BaseRequest request) na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\Utils\RequestHelpers.cs:linha 75
   em GuiStracini.Mandae.Utils.ServiceFactory.&lt;Execute&gt;d__5`2.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\Utils\ServiceFactory.cs:linha 86
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   em GuiStracini.Mandae.Utils.ServiceFactory.&lt;Delete&gt;d__13`2.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\Utils\ServiceFactory.cs:linha 213
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   em GuiStracini.Mandae.MandaeClient.&lt;CancelOrderItemCollectRequestAsync&gt;d__21.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae\MandaeClient.cs:linha 361
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em GuiStracini.Mandae.Test.OrdersTest.&lt;CancelOrderItemCollectRequestAsync&gt;d__10.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 248
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>GetLatestOrderCollectStatus</span></span> <span class="richText"><span class="t0">[0:00.432] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsNotNull failed. 
   em GuiStracini.Mandae.Test.OrdersTest.GetLatestOrderCollectStatus() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 183


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>GetLatestOrderCollectStatusAsync</span></span> <span class="richText"><span class="t0">[0:00.451] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsNotNull failed. 
   em GuiStracini.Mandae.Test.OrdersTest.&lt;GetLatestOrderCollectStatusAsync&gt;d__6.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 197
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>RegisterLargeOrderCollectRequest</span></span> <span class="richText"><span class="t0">[0:00.459] Failed</span></span><br /><span class="richText"><span class="t2">Assert.AreNotEqual failed. Expected any value except:&lt;00000000-0000-0000-0000-000000000000&gt;. Actual:&lt;00000000-0000-0000-0000-000000000000&gt;. 
   em GuiStracini.Mandae.Test.OrdersTest.RegisterLargeOrderCollectRequest() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 156


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>RegisterLargeOrderCollectRequestAsync</span></span> <span class="richText"><span class="t0">[0:00.460] Failed</span></span><br /><span class="richText"><span class="t2">Assert.AreNotEqual failed. Expected any value except:&lt;00000000-0000-0000-0000-000000000000&gt;. Actual:&lt;00000000-0000-0000-0000-000000000000&gt;. 
   em GuiStracini.Mandae.Test.OrdersTest.&lt;RegisterLargeOrderCollectRequestAsync&gt;d__4.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 172
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>RegisterOrderCollectRequest</span></span> <span class="richText"><span class="t0">[0:00.465] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsTrue failed. 
   em GuiStracini.Mandae.Test.OrdersTest.RegisterOrderCollectRequest() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 127


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>RegisterOrderCollectRequestAsync</span></span> <span class="richText"><span class="t0">[0:00.449] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsTrue failed. 
   em GuiStracini.Mandae.Test.OrdersTest.&lt;RegisterOrderCollectRequestAsync&gt;d__2.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\OrdersTest.cs:linha 142
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)


</span></span></div><div style="margin-left: 40px"><i class="i1"></i><span class="richText"><span>RatesTest</span></span> <span class="richText"><span>(2 tests)</span></span> <span class="richText"><span class="t1">[0:02.292] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>GetRates</span></span> <span class="richText"><span class="t1">[0:01.165] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>GetRatesAsync</span></span> <span class="richText"><span class="t1">[0:01.127] Success</span></span></div><div style="margin-left: 40px"><i class="i1"></i><span class="richText"><span>RequestHelpersTest</span></span> <span class="richText"><span>(6 tests)</span></span> <span class="richText"><span class="t1">[0:00.003] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>RequestAdditionalParameter</span></span> <span class="richText"><span class="t1">[0:00.000] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>RequestAdditionalParameterAsQueryString</span></span> <span class="richText"><span class="t1">[0:00.000] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>RequestAdditionalParameterIncorrectActionMethod</span></span> <span class="richText"><span class="t1">[0:00.000] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>RequestEndPointWithMultipleParameters</span></span> <span class="richText"><span class="t1">[0:00.001] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>RequestEndPointWithMultipleParametersWithInvalidData</span></span> <span class="richText"><span class="t1">[0:00.001] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>RequestEndPointWithNullValues</span></span> <span class="richText"><span class="t1">[0:00.000] Success</span></span></div><div style="margin-left: 40px"><i class="i1"></i><span class="richText"><span>SchedulingTest</span></span> <span class="richText"><span>(2 tests)</span></span> <span class="richText"><span class="t1">[0:01.158] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>GetAvailableHours</span></span> <span class="richText"><span class="t1">[0:00.416] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>GetAvailableHoursAsync</span></span> <span class="richText"><span class="t1">[0:00.741] Success</span></span></div><div style="margin-left: 40px"><i class="i0"></i><span class="richText"><span>TrackingTest</span></span> <span class="richText"><span>(2 tests)</span></span> <span class="richText"><span class="t0">[0:00.900] Failed: 2 tests failed</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>GetTracking</span></span> <span class="richText"><span class="t0">[0:00.460] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsNotNull failed. 
   em GuiStracini.Mandae.Test.TrackingTest.GetTracking() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\TrackingTest.cs:linha 36


</span></span></div><div style="margin-left: 60px"><i class="i0"></i><span class="richText"><span>GetTrackingAsync</span></span> <span class="richText"><span class="t0">[0:00.440] Failed</span></span><br /><span class="richText"><span class="t2">Assert.IsNotNull failed. 
   em GuiStracini.Mandae.Test.TrackingTest.&lt;GetTrackingAsync&gt;d__1.MoveNext() na C:\Users\Guilherme\Desktop\GuiStracini.Mandae\GuiStracini.Mandae.Tests\TrackingTest.cs:linha 51
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)


</span></span></div><div style="margin-left: 40px"><i class="i1"></i><span class="richText"><span>VehiclesTest</span></span> <span class="richText"><span>(2 tests)</span></span> <span class="richText"><span class="t1">[0:00.874] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>GetVehicles</span></span> <span class="richText"><span class="t1">[0:00.439] Success</span></span></div><div style="margin-left: 60px"><i class="i1"></i><span class="richText"><span>GetVehiclesAsync</span></span> <span class="richText"><span class="t1">[0:00.434] Success</span></span></div></div></html>